import { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

type Health = Record<string, { ok?: boolean; detail?: string; version?: string; freeBytes?: number; environment?: string | null }>
type Job = { id: string; action: string; status: string; created_at: number }
type Skill = { skill_id: string; version: string; kind: string; source: string; mutable: boolean; path: string; error?: string; license?: string; actions?: Record<string, { title: string }>; permissions?: { filesystem: { read: string[]; write: string[] }; network: boolean; subprocess: boolean; robotState: boolean; robotCommand: boolean } }
type Robot = { id: string; name: string; version: string; maturity?: string; capabilities: string[]; path: string; compatibility?: { skillId: string; version: string; compatible: boolean; reasons: string[] }[] }
type Artifact = { sha256: string; size: number; media_type?: string }
const API = '/api/v1'

async function get<T>(path: string): Promise<T> { const response = await fetch(`${API}${path}`); if (!response.ok) throw new Error(await response.text()); return response.json() as Promise<T> }
function Badge({ value }: { value: string }) { const tone = /SUCCEEDED|true|simulation/i.test(value) ? 'ok' : /FAILED|CANCELLED|false/i.test(value) ? 'bad' : 'warn'; return <span className={`badge ${tone}`}>{value}</span> }
function Empty({ children }: { children: React.ReactNode }) { return <p className="empty">{children}</p> }

function Dashboard() {
  const [health, setHealth] = useState<Health | null>(null); const [jobs, setJobs] = useState<Job[]>([])
  useEffect(() => { void Promise.all([get<Health>('/health'), get<Job[]>('/jobs')]).then(([h, j]) => { setHealth(h); setJobs(j.slice(0, 6)) }) }, [])
  return <><header><div><h1>工作台</h1><p>本地控制面状态与最近运行记录。</p></div></header><section className="health-grid">{health ? Object.entries(health).map(([name, value]) => <article key={name}><strong>{name}</strong><Badge value={value.ok ? '健康' : '待配置'} /><small>{value.detail || value.version || value.environment || '—'}</small></article>) : <Empty>正在读取健康状态…</Empty>}</section><h2>最近 Job</h2><JobTable jobs={jobs} /></>
}
function JobTable({ jobs }: { jobs: Job[] }) { return jobs.length ? <table><thead><tr><th>状态</th><th>Action</th><th>Job</th><th>运行时间</th></tr></thead><tbody>{jobs.map(job => <tr key={job.id}><td><Badge value={job.status} /></td><td><code>{job.action}</code></td><td><code title={job.id}>{job.id.slice(0, 12)}</code></td><td>{Math.max(0, Math.floor(Date.now() / 1000 - job.created_at))} s</td></tr>)}</tbody></table> : <Empty>暂无 Job。可从 Skills 的 action 或 CLI 创建运行。</Empty> }
function Robots() { const [items, setItems] = useState<Robot[]>([]); useEffect(() => { void get<Robot[]>('/robots').then(setItems) }, []); return <><header><div><h1>机器人</h1><p>Profile、成熟度与 Skill × Profile 兼容性矩阵。</p></div></header>{items.length ? <table><thead><tr><th>Profile</th><th>版本</th><th>成熟度</th><th>Capabilities</th><th>兼容 Skills</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td><strong>{item.name || item.id}</strong><small><code>{item.id}</code></small></td><td>{item.version}</td><td><Badge value={item.maturity || 'unknown'} /></td><td>{item.capabilities.join(', ') || '—'}</td><td>{item.compatibility?.length ? item.compatibility.map(entry => <small key={`${entry.skillId}-${entry.version}`}><Badge value={entry.compatible ? '兼容' : '不兼容'} /> <code>{entry.skillId}@{entry.version}</code></small>) : '—'}</td></tr>)}</tbody></table> : <Empty>尚未发现 Robot Profile。</Empty>}</> }
function Skills() { const [items, setItems] = useState<Skill[]>([]); const [source, setSource] = useState(''); const [message, setMessage] = useState(''); const refresh = () => void get<Skill[]>('/skills').then(setItems); useEffect(refresh, []); async function install() { const response = await fetch(`${API}/skills/install`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ source }) }); setMessage(response.ok ? '已安装固定版本；列表已刷新。' : `安装失败：${await response.text()}`); if (response.ok) refresh() } async function invoke(item: Skill, action: string) { const raw = window.prompt(`输入 ${action} 参数（JSON object）`, action === 'inspect' ? '{"mjcf_path":"/absolute/path/to/model.xml"}' : '{}'); if (raw === null) return; try { const response = await fetch(`${API}/skills/${item.skill_id}/actions/${action}:invoke`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ parameters: JSON.parse(raw) }) }); setMessage(response.ok ? `已创建 Job：${(await response.json()).id}` : `调用失败：${await response.text()}`) } catch { setMessage('参数必须是 JSON object。') } } return <><header><div><h1>Skills</h1><p>固定版本、权限与 action 均来自 manifest。首次执行会创建独立 Job。</p></div></header><div className="install"><input value={source} onChange={event => setSource(event.target.value)} placeholder="本地 RoboLab-Skill checkout 内的 Skill 路径"/><button onClick={install} disabled={!source}>安装 Skill</button></div>{message && <p className="notice">{message}</p>}{items.length ? <table><thead><tr><th>Skill</th><th>版本 / 来源</th><th>权限</th><th>Actions</th></tr></thead><tbody>{items.map(item => <tr key={item.path}><td><strong>{item.skill_id || '无效 manifest'}</strong><small>{item.kind} · {item.license || '—'} · <Badge value={item.mutable ? '开发中（可变）' : '已固定'} /></small></td><td>{item.version}<small><code>{item.source}</code></small></td><td><small>读：{item.permissions?.filesystem.read.join(', ') || '—'}<br/>网络：{String(item.permissions?.network)} · 机器人命令：{String(item.permissions?.robotCommand)}</small></td><td>{item.actions ? Object.entries(item.actions).map(([id, detail]) => <button className="action" key={id} title={detail.title} onClick={() => void invoke(item, id)}>{id}</button>) : '—'}</td></tr>)}</tbody></table> : <Empty>尚未安装 Skill。输入 local catalog checkout 中的包路径以安装固定版本。</Empty>}</> }
function Jobs() { const [items, setItems] = useState<Job[]>([]); const [selected, setSelected] = useState<Job | null>(null); const [logs, setLogs] = useState(''); const refresh = () => void get<Job[]>('/jobs').then(setItems); useEffect(refresh, []); useEffect(() => { if (!selected) return; const load = () => void get<{ stdout: string; stderr: string; events: string }>(`/jobs/${selected.id}/logs`).then(log => setLogs(`${log.events}${log.stdout}${log.stderr}`)); load(); const timer = window.setInterval(() => { load(); refresh() }, 1000); return () => window.clearInterval(timer) }, [selected]); async function cancel() { if (!selected) return; await fetch(`${API}/jobs/${selected.id}/cancel`, { method: 'POST' }); refresh() } return <><header><div><h1>Jobs</h1><p>阶段、运行时间与每秒更新的诊断日志。</p></div><button onClick={refresh}>刷新</button></header><div className="split"><div><JobTable jobs={items} /><div className="job-picker">{items.map(item => <button key={item.id} onClick={() => setSelected(item)}>{item.id.slice(0, 8)}</button>)}</div></div><aside><h2>{selected ? selected.action : '选择一个 Job'}</h2>{selected ? <><p><Badge value={selected.status} /></p><button className="danger" onClick={cancel} disabled={!/CREATED|RUNNING/.test(selected.status)}>停止 Job</button><pre>{logs || '尚无日志'}</pre></> : <Empty>选择左侧 Job 查看日志与取消操作。</Empty>}</aside></div></> }
function Artifacts() { const [items, setItems] = useState<Artifact[]>([]); useEffect(() => { void get<Artifact[]>('/artifacts').then(setItems) }, []); return <><header><div><h1>Artifacts</h1><p>内容寻址产物及其固定哈希。</p></div></header>{items.length ? <table><thead><tr><th>SHA-256</th><th>大小</th><th>类型</th></tr></thead><tbody>{items.map(item => <tr key={item.sha256}><td><a href={`${API}/artifacts/${item.sha256}`}><code>{item.sha256}</code></a></td><td>{item.size.toLocaleString()} B</td><td>{item.media_type || '—'}</td></tr>)}</tbody></table> : <Empty>暂无归档产物。运行 Inspector 或其他 PlatformSkill 后会显示在这里。</Empty>}</> }
function Settings() { return <><header><div><h1>设置</h1><p>本机模式，无远程账户或网络服务。</p></div></header><dl><dt>API</dt><dd><code>127.0.0.1</code> loopback only</dd><dt>数据目录</dt><dd><code>var/</code></dd><dt>命令行</dt><dd><code>robolab serve</code> / <code>robolab check</code></dd></dl></> }
const pages = { 'Dashboard': Dashboard, 'Robots': Robots, 'Skills': Skills, 'Jobs': Jobs, 'Artifacts': Artifacts, 'Settings': Settings }
function App() { const [page, setPage] = useState<keyof typeof pages>('Dashboard'); const Page = pages[page]; return <div className="shell"><nav><div className="brand">RoboLab<span>LOCAL WORKSPACE</span></div>{Object.keys(pages).map(name => <button key={name} className={page === name ? 'active' : ''} onClick={() => setPage(name as keyof typeof pages)}>{name}</button>)}</nav><main><Page /></main></div> }
createRoot(document.getElementById('root')!).render(<App />)
